-- Ejecutar conectado como SYSTEM dentro de FREEPDB1.
CREATE USER INVENTARIODB IDENTIFIED BY 1234567;
GRANT CREATE SESSION, CREATE TABLE, CREATE SEQUENCE, CREATE VIEW, CREATE PROCEDURE TO INVENTARIODB;
ALTER USER INVENTARIODB QUOTA UNLIMITED ON USERS;
